\chapter{Tests in Python}
\label{ch:python}

\section{Introduction}

There is a Python module for accessing NetCDF files. We provide a patch (Section \ref{sec:patch}) to this module to support ESDM.
The patch and instructions to run the tests are available in the directory \texttt{esdm-netcdf/dev}.
The procedures to run the tests are following.

Run the build script:

\begin{framed}
\$ ./build.sh
\end{framed}

Python tests are created now inside the directory \texttt{dev/netcdf4-python/test}.
Go to that directory.

\begin{framed}
\$ cd netcdf4-python/test
\end{framed}

Now, copy or link the \texttt{\_esdm.conf} file to this directory.
This can be done using a copy from the directory \texttt{esdm-netcdf/dev}.

\section{Patch}
\label{sec:patch}

The changings in the original patch to include ESDM can be seen next.
Basically, we add the flags HAS\_ESDM\_SUPPORT, NC\_FORMATX\_ESDM, NC\_ESDM and fmt == `ESDM' (ESDM format).\\

\begin{lstlisting}[language=python,upquote=true]
diff --git a/include/netCDF4.pxi b/include/netCDF4.pxi
index 625752a..7bcd019 100644
--- a/include/netCDF4.pxi
+++ b/include/netCDF4.pxi
@@ -49,6 +49,7 @@ cdef extern from "netcdf.h":
         NC_WRITE # read & write
         # Use these 'mode' flags for nc_create.
         NC_CLOBBER
+        NC_ESDM # ESDM support for Python
         NC_NOCLOBBER # Don't destroy existing file on create
         NC_64BIT_OFFSET # Use large (64-bit) file offsets
         NC_64BIT_DATA # Use cdf-5 format
@@ -122,6 +123,7 @@ cdef extern from "netcdf.h":
         NC_FORMAT_NC3
         NC_FORMAT_NC_HDF4
         NC_FORMAT_NC_HDF5
+        NC_FORMATX_ESDM
         NC_FORMAT_DAP2
         NC_FORMAT_DAP4
         NC_FORMAT_PNETCDF
@@ -704,7 +706,7 @@ IF HAS_NC_CREATE_MEM:
             int flags
         int nc_close_memio(int ncid, NC_memio* info);

-IF HAS_PARALLEL4_SUPPORT or HAS_PNETCDF_SUPPORT:
+IF HAS_PARALLEL4_SUPPORT or HAS_PNETCDF_SUPPORT or HAS_ESDM_SUPPORT:
     cdef extern from "mpi-compat.h": pass
     cdef extern from "netcdf_par.h":
         ctypedef int MPI_Comm
diff --git a/netCDF4/_netCDF4.pyx b/netCDF4/_netCDF4.pyx
index b693354..58d02e8 100644
--- a/netCDF4/_netCDF4.pyx
+++ b/netCDF4/_netCDF4.pyx
@@ -1264,7 +1264,7 @@ import_array()
 include "constants.pyx"
 include "membuf.pyx"
 include "netCDF4.pxi"
-IF HAS_PARALLEL4_SUPPORT or HAS_PNETCDF_SUPPORT:
+IF HAS_PARALLEL4_SUPPORT or HAS_PNETCDF_SUPPORT or HAS_ESDM_SUPPORT:
     cimport mpi4py.MPI as MPI
     from mpi4py.libmpi cimport MPI_Comm, MPI_Info, MPI_Comm_dup, MPI_Info_dup, \
                                MPI_Comm_free, MPI_Info_free, MPI_INFO_NULL,\
@@ -1344,11 +1344,13 @@ _intnptonctype  = {'i1' : NC_BYTE,
 # create dictionary mapping string identifiers to netcdf format codes
 _format_dict  = {'NETCDF3_CLASSIC' : NC_FORMAT_CLASSIC,
                  'NETCDF4_CLASSIC' : NC_FORMAT_NETCDF4_CLASSIC,
-                 'NETCDF4'         : NC_FORMAT_NETCDF4}
+                 'NETCDF4'         : NC_FORMAT_NETCDF4,
+                 'ESDM'            : NC_FORMATX_ESDM}
 # create dictionary mapping string identifiers to netcdf create format codes
 _cmode_dict  = {'NETCDF3_CLASSIC' : NC_CLASSIC_MODEL,
                 'NETCDF4_CLASSIC' : NC_CLASSIC_MODEL | NC_NETCDF4,
-                'NETCDF4'         : NC_NETCDF4}
+                'NETCDF4'         : NC_NETCDF4,
+                'ESDM'            : NC_ESDM}
 IF HAS_CDF5_FORMAT:
     # NETCDF3_64BIT deprecated, saved for compatibility.
     # use NETCDF3_64BIT_OFFSET instead.
@@ -1547,6 +1549,8 @@ cdef _get_full_format(int grpid):
             return 'DAP2'
         elif formatp == NC_FORMAT_DAP4:
             return 'DAP4'
+        elif formatp == NC_FORMATX_ESDM:
+            return 'ESDM'
         elif formatp == NC_FORMAT_UNDEFINED:
             return 'UNDEFINED'
     ELSE:
@@ -1578,7 +1582,7 @@ be raised in the next release."""
                 PyMem_Free(string_ptrs)
         else:
             # don't allow string array attributes in NETCDF3 files.
-            if is_netcdf3 and N > 1:
+            if is_netcdf3 and N > 1 and fmt != 'ESDM':
                 msg='array string attributes can only be written with NETCDF4'
                 raise IOError(msg)
             if not value_arr.shape:
@@ -1593,7 +1597,7 @@ be raised in the next release."""
     # if array is 64 bit integers or
     # if 64-bit datatype not supported, cast to 32 bit integers.
     fmt = _get_format(grp._grpid)
-    is_netcdf3 = fmt.startswith('NETCDF3') or fmt == 'NETCDF4_CLASSIC'
+    is_netcdf3 = fmt.startswith('NETCDF3') or fmt == 'NETCDF4_CLASSIC' or fmt == 'ESDM'
     if value_arr.dtype.str[1:] == 'i8' and ('i8' not in _supportedtypes or\
        (is_netcdf3 and fmt != 'NETCDF3_64BIT_DATA')):
         value_arr = value_arr.astype('i4')
@@ -2030,7 +2034,7 @@ strings.
     __pdoc__['Dataset.data_model']=\
     """`data_model` describes the netCDF
     data model version, one of `NETCDF3_CLASSIC`, `NETCDF4`,
-    `NETCDF4_CLASSIC`, `NETCDF3_64BIT_OFFSET` or `NETCDF3_64BIT_DATA`."""
+    `NETCDF4_CLASSIC`, `NETCDF3_64BIT_OFFSET` or `NETCDF3_64BIT_DATA` or ESDM."""
     __pdoc__['Dataset.file_format']=\
     """same as `data_model`, retained for backwards compatibility."""
     __pdoc__['Dataset.disk_format']=\
@@ -2084,7 +2088,7 @@ strings.

         **`format`**: underlying file format (one of `'NETCDF4',
         'NETCDF4_CLASSIC', 'NETCDF3_CLASSIC'`, `'NETCDF3_64BIT_OFFSET'` or
-        `'NETCDF3_64BIT_DATA'`.
+        `'NETCDF3_64BIT_DATA'` or ESDM.
         Only relevant if `mode = 'w'` (if `mode = 'r','a'` or `'r+'` the file format
         is automatically detected). Default `'NETCDF4'`, which means the data is
         stored in an HDF5 file, using netCDF 4 API features.  Setting
@@ -2156,7 +2160,7 @@ strings.
         cdef char *path
         cdef char namstring[NC_MAX_NAME+1]
         cdef int cmode
-        IF HAS_PARALLEL4_SUPPORT or HAS_PNETCDF_SUPPORT:
+        IF HAS_PARALLEL4_SUPPORT or HAS_PNETCDF_SUPPORT or HAS_ESDM_SUPPORT:
             cdef MPI_Comm mpicomm
             cdef MPI_Info mpiinfo

@@ -2183,7 +2187,7 @@ strings.
                 msg='parallel mode requires MPI enabled netcdf-c'
                 raise ValueError(msg)
             ELSE:
-                parallel_formats = []
+                parallel_formats = ['ESDM']
                 IF HAS_PARALLEL4_SUPPORT:
                     parallel_formats += ['NETCDF4','NETCDF4_CLASSIC']
                 IF HAS_PNETCDF_SUPPORT:
@@ -2222,7 +2226,7 @@ strings.
             else:
                 if clobber:
                     if parallel:
-                        IF HAS_PARALLEL4_SUPPORT or HAS_PNETCDF_SUPPORT:
+                        IF HAS_PARALLEL4_SUPPORT or HAS_PNETCDF_SUPPORT or HAS_ESDM_SUPPORT:
                             ierr = nc_create_par(path, NC_CLOBBER | cmode, \
                                    mpicomm, mpiinfo, &grpid)
                         ELSE:
@@ -2272,7 +2276,7 @@ strings.
         version 4.4.1 or higher of the netcdf C lib, and rebuild netcdf4-python."""
                     raise ValueError(msg)
             elif parallel:
-                IF HAS_PARALLEL4_SUPPORT or HAS_PNETCDF_SUPPORT:
+                IF HAS_PARALLEL4_SUPPORT or HAS_PNETCDF_SUPPORT or HAS_ESDM_SUPPORT:
                     ierr = nc_open_par(path, NC_NOWRITE | NC_MPIIO, \
                            mpicomm, mpiinfo, &grpid)
                 ELSE:
@@ -2853,7 +2857,7 @@ Use if you need to ensure that a netCDF attribute is created with type
 `NC_STRING` if the file format is `NETCDF4`."""
         cdef nc_type xtype
         xtype=-99
-        if self.data_model != 'NETCDF4':
+        if self.data_model != 'NETCDF4' and self.data_model != 'ESDM':
             msg='file format does not support NC_STRING attributes'
             raise IOError(msg)
         _set_att(self, NC_GLOBAL, name, value, xtype=xtype, force_ncstring=True)
@@ -3435,7 +3435,7 @@ return the group that this `netCDF4.Dimension` is a member of."""
 returns `True` if the `netCDF4.Dimension` instance is unlimited, `False` otherwise."""
         cdef int ierr, n, numunlimdims, ndims, nvars, ngatts, xdimid
         cdef int *unlimdimids
-        if self._data_model == 'NETCDF4':
+        if self._data_model == 'NETCDF4' or self._data_model == "ESDM":
             ierr = nc_inq_unlimdims(self._grpid, &numunlimdims, NULL)
             _ensure_nc_success(ierr)
             if numunlimdims == 0:
@@ -4138,7 +4138,7 @@ Use if you need to ensure that a netCDF attribute is created with type
 Use if you need to set an attribute to an array of variable-length strings."""
         cdef nc_type xtype
         xtype=-99
-        if self._grp.data_model != 'NETCDF4':
+        if self._grp.data_model != 'NETCDF4' and self._grp.data_model != 'ESDM':
             msg='file format does not support NC_STRING attributes'
             raise IOError(msg)
         _set_att(self._grp, self._varid, name, value, xtype=xtype, force_ncstring=True)
diff --git a/setup.py b/setup.py
index febc020..d7ba091 100644
--- a/setup.py
+++ b/setup.py
@@ -58,6 +58,7 @@ def check_api(inc_dirs):
     has_nc_create_mem = False
     has_parallel4_support = False
     has_pnetcdf_support = False
+    has_esdm_support = False

     for d in inc_dirs:
         try:
@@ -564,6 +565,7 @@ if 'sdist' not in sys.argv[1:] and 'clean' not in sys.argv[1:]:
     else:
         sys.stdout.write('netcdf lib does not have pnetcdf parallel functions\n')
         f.write('DEF HAS_PNETCDF_SUPPORT = 0\n')
+    f.write('DEF HAS_ESDM_SUPPORT = 1\n') # TODO Fixme

     f.close()
\end{lstlisting}

\section{Tests}

Similarly to what happened with the tests in C, the tests in Python mix functionalities that are not yet available in ESDM.
In this case, we opt to just present the results using the original NetCDF tests without any modification.
As expected, not many tests are sucessful using ESDM directly, for the reasons mentioned in Chapter \ref{ch:nctests}.

Hopefully, the positive results are enough to prove the compatibility between the current version of ESDM and NetCDF Python.

\begin{table}[H]
\centering
\begin{tabular}{|l|c|c|}
\hline
\multicolumn{1}{|c|}{Filename}          & \multicolumn{1}{c|}{Success} & \multicolumn{1}{c|}{Failure} \\ \hline \hline
tst\_atts.py                            &                              &      $\checkmark$         \\ \hline
tst\_cdf5.py                            &                              &      $\checkmark$         \\ \hline
tst\_compound\_alignment.py             &                              &      $\checkmark$         \\ \hline
tst\_compoundatt.py                     &                              &      $\checkmark$         \\ \hline
tst\_compoundvar.py                     &                              &      $\checkmark$         \\ \hline
tst\_compression.py                     &                              &      $\checkmark$         \\ \hline
tst\_create\_mem.py                     &          $\checkmark$        &                           \\ \hline
tst\_dap.py                             &                              &      $\checkmark$         \\ \hline
tst\_dims.py                            &                              &      $\checkmark$         \\ \hline
tst\_diskless.py                        &                              &      $\checkmark$         \\ \hline
tst\_endian.py                          &                              &      $\checkmark$         \\ \hline
tst\_enum.py                            &                              &      $\checkmark$         \\ \hline
tst\_fancyslicing.py                    &                              &      $\checkmark$         \\ \hline
tst\_filepath.py                        &                              &      $\checkmark$         \\ \hline
tst\_get\_variables\_by\_attributes.py  &          $\checkmark$        &                           \\ \hline
tst\_grps2.py                           &                              &      $\checkmark$         \\ \hline
tst\_grps.py                            &                              &      $\checkmark$         \\ \hline
tst\_issue908.py                        &          $\checkmark$        &                           \\ \hline
tst\_masked2.py                         &                              &      $\checkmark$         \\ \hline
tst\_masked3.py                         &                              &      $\checkmark$         \\ \hline
tst\_masked4.py                         &                              &      $\checkmark$         \\ \hline
tst\_masked5.py                         &                              &      $\checkmark$         \\ \hline
tst\_masked6.py                         &                              &      $\checkmark$         \\ \hline
tst\_masked.py                          &                              &      $\checkmark$         \\ \hline
tst\_multifile2.py                      &                              &      $\checkmark$         \\ \hline
tst\_multifile.py                       &                              &      $\checkmark$         \\ \hline
tst\_open\_mem.py                       &                              &      $\checkmark$         \\ \hline
tst\_refcount.py                        &                              &      $\checkmark$         \\ \hline
tst\_rename.py                          &                              &      $\checkmark$         \\ \hline
tst\_scalarvar.py                       &                              &      $\checkmark$         \\ \hline
tst\_scaled.py                          &                              &      $\checkmark$         \\ \hline
tst\_shape.py                           &                              &      $\checkmark$         \\ \hline
tst\_slicing.py                         &                              &      $\checkmark$         \\ \hline
tst\_stringarr.py                       &          $\checkmark$        &                           \\ \hline
tst\_types.py                           &                              &      $\checkmark$         \\ \hline
tst\_unicode3.py                        &                              &      $\checkmark$         \\ \hline
tst\_unicodeatt.py                      &                              &      $\checkmark$         \\ \hline
tst\_unicode.py                         &                              &      $\checkmark$         \\ \hline
tst\_unlimdim.py                        &                              &      $\checkmark$         \\ \hline
tst\_Unsigned.py                        &          $\checkmark$        &                           \\ \hline
tst\_utils.py                           &          $\checkmark$        &                           \\ \hline
tst\_vars.py                            &                              &      $\checkmark$         \\ \hline
tst\_vlen.py                            &                              &      $\checkmark$         \\ \hline
\multicolumn{1}{|c|}{Total Files: 43}   & \multicolumn{1}{c|}{6}       & \multicolumn{1}{c|}{37}   \\ \hline
\hline
\end{tabular}
\caption{\label{tab:python} Current status of all tests}
\end{table}

\begin{comment}

PLEASE, CHECK

In installing the tests, I got this message. However, is does not look it change anything for the tests themselves.

Error compiling Cython file:
------------------------------------------------------------
...
                 'ESDM'            : NC_FORMATX_ESDM}
# create dictionary mapping string identifiers to netcdf create format codes
_cmode_dict  = {'NETCDF3_CLASSIC' : NC_CLASSIC_MODEL,
                'NETCDF4_CLASSIC' : NC_CLASSIC_MODEL | NC_NETCDF4,
                'NETCDF4'         : NC_NETCDF4,
                'ESDM'            : NC_ESDM}
                                          ^
------------------------------------------------------------

netCDF4/_netCDF4.pyx:1310:43: undeclared name not builtin: NC_ESDM
building 'netCDF4._netCDF4' extension
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/netCDF4
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/lucy/esiwace/esdm/install/include -I/usr/include/openmpi -I/usr/include/hdf5/openmpi -I/usr/include/openmpi -I/usr/include/hdf5/openmpi -I/usr/lib/python3/dist-packages/numpy/core/include -I/usr/lib/python3/dist-packages/mpi4py/include -Iinclude -I/usr/include/python3.6m -c netCDF4/_netCDF4.c -o build/temp.linux-x86_64-3.6/netCDF4/_netCDF4.o
netCDF4/_netCDF4.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
 #error Do not use this file, it is the result of a failed Cython compilation.
  ^~~~~
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Check that the right NetCDF library is used
ldd: build/lib.linux-x86_64-3.6/netCDF4/_netCDF4.cpython-36m-x86_64-linux-gnu.so: No such file or directory
Setup ESDM as target for tempfiles

\end{comment}

\begin{comment}

CHECK PLEASE

This is the old section for the tests. At this moment, I don't think it has to be updated.

\section{Tests}

The next sections introduce information about each Python test. For them to run with ESDM, two strings were replaced in all tests that contain them. The commands for this substitution can be found in the file \texttt{build.sh}.

\begin{verbatim}
sed -i 's#tempfile.NamedTemporaryFile(.*delete=False).name#"esdm://testfile'$RANDOM'"#'  *.py
sed -i 's#os.remove(self.file.*#pass#'  *.py
\end{verbatim}

\subsection{Test tst\_atts.py}

\begin{verbatim}
E[ESDM NC] called ESDM_close:668 65536

======================================================================
ERROR: runTest (__main__.VariablesTestCase)
testing attributes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_atts.py", line 53, in setUp
    f.stringseqatt = STRINGSEQATT
  File "NetCDF4/_NetCDF4.pyx", line 2918, in NetCDF4._NetCDF4.Dataset.__setattr__
  File "NetCDF4/_NetCDF4.pyx", line 2848, in NetCDF4._NetCDF4.Dataset.setncattr
  File "NetCDF4/_NetCDF4.pyx", line 1587, in NetCDF4._NetCDF4._set_att
OSError: array string attributes can only be written with NETCDF4

----------------------------------------------------------------------
\end{verbatim}

\subsection{Test tst\_cdf5.py}

\begin{verbatim}
[ESDM NC] called ESDM_get_att:1356 65536
F
======================================================================
FAIL: runTest (__main__.test_cdf5)
testing NETCDF3_64BIT_DATA format (CDF-5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_cdf5.py", line 34, in runTest
    assert (type(f.int64_attr) == np.int64)
AssertionError

----------------------------------------------------------------------
\end{verbatim}

\subsection{Test tst\_compound\_alignment.py}

\begin{verbatim}
[ESDM NC] called ESDM__enddef:619 65536
E
======================================================================
ERROR: runTest (__main__.CompoundAlignTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_compound_alignment.py", line 90, in setUp
    v_cells = dataset.createVariable("cells",cell_cmp_dtype,"number_cells")
  File "NetCDF4/_NetCDF4.pyx", line 2772, in NetCDF4._NetCDF4.Dataset.createVariable
  File "NetCDF4/_NetCDF4.pyx", line 3809, in NetCDF4._NetCDF4.Variable.__init__
  File "NetCDF4/_NetCDF4.pyx", line 1891, in NetCDF4._NetCDF4._ensure_nc_success
RuntimeError: NetCDF: Not a valid data type or _FillValue type mismatch

----------------------------------------------------------------------
\end{verbatim}

\subsection{Test tst\_compoundatt.py}

\begin{verbatim}
[ESDM NC] called ESDM__enddef:619 65536
E
======================================================================
ERROR: runTest (__main__.VariablesTestCase)
testing compound attributes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_compoundatt.py", line 36, in setUp
    v = f.createVariable(VAR_NAME,wind_vector_type, DIM_NAME)
  File "NetCDF4/_NetCDF4.pyx", line 2772, in NetCDF4._NetCDF4.Dataset.createVariable
  File "NetCDF4/_NetCDF4.pyx", line 3809, in NetCDF4._NetCDF4.Variable.__init__
  File "NetCDF4/_NetCDF4.pyx", line 1891, in NetCDF4._NetCDF4._ensure_nc_success
RuntimeError: NetCDF: Not a valid data type or _FillValue type mismatch

----------------------------------------------------------------------
Ran 1 test in 0.002s
\end{verbatim}

\subsection{Test tst\_compoundvar.py}

\begin{verbatim}
[ESDM NC] called ESDM_inq:826 65536
E
======================================================================
ERROR: runTest (__main__.VariablesTestCase)
testing compound variables
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_compoundvar.py", line 60, in setUp
    g = f.groups[GROUP_NAME]
KeyError: 'phony_group'

----------------------------------------------------------------------
\end{verbatim}

\subsection{Test tst\_compression.py}

\begin{verbatim}
[ESDM NC] called ESDM_close:668 65536
E
======================================================================
ERROR: runTest (__main__.CompressionTestCase)
testing zlib and shuffle compression filters
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_compression.py", line 70, in runTest
    uncompressed_size = os.stat(self.files[0]).st_size
FileNotFoundError: [Errno 2] No such file or directory: 'esdm://testfile12246'

----------------------------------------------------------------------
\end{verbatim}

\subsection{Test tst\_create\_mem.py}

\begin{verbatim}
OK

[ESDM NC] called ESDM_open:467 test2.nc 65536 0 test2.nc
E
======================================================================
ERROR: test_mem_create (__main__.TestCreateMem)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_create_mem.py", line 22, in test_mem_create
    check_inmemory('NETCDF3_CLASSIC')
  File "tst\_create_mem.py", line 19, in check_inmemory
    nc2 = NetCDF4.Dataset('test2.nc','r',memory=b)
  File "NetCDF4/_NetCDF4.pyx", line 2325, in NetCDF4._NetCDF4.Dataset.__init__
  File "NetCDF4/_NetCDF4.pyx", line 1889, in NetCDF4._NetCDF4._ensure_nc_success
OSError: [Errno -77] NetCDF: Access failure: b'test2.nc'

----------------------------------------------------------------------
\end{verbatim}

\subsection{Test tst\_dap.py}

\begin{verbatim}
[ESDM NC] called ESDM_open:467 http://remotetest.unidata.ucar.edu/thredds/dodsC/testdods/testData.nc 65536 0 http://remotetest.unidata.ucar.edu/thredds/dodsC/testdods/testData.nc
E
======================================================================
ERROR: runTest (__main__.DapTestCase)
testing access of data over http using opendap
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_dap.py", line 23, in runTest
    ncfile = NetCDF4.Dataset(URL)
  File "NetCDF4/_NetCDF4.pyx", line 2325, in NetCDF4._NetCDF4.Dataset.__init__
  File "NetCDF4/_NetCDF4.pyx", line 1889, in NetCDF4._NetCDF4._ensure_nc_success
OSError: [Errno -77] NetCDF: Access failure: b'http://remotetest.unidata.ucar.edu/thredds/dodsC/testdods/testData.nc'

----------------------------------------------------------------------
\end{verbatim}

\subsection{Test tst\_dims.py}

\begin{verbatim}
[ESDM NC] WARN ESDM_def_grp():2203. ESDM does not support groups from NetCDF!
E
======================================================================
ERROR: runTest (__main__.DimensionsTestCase)
testing dimensions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_dims.py", line 38, in setUp
    g.createDimension(LAT_NAME,LAT_LENG)
  File "NetCDF4/_NetCDF4.pyx", line 2566, in NetCDF4._NetCDF4.Dataset.createDimension
  File "NetCDF4/_NetCDF4.pyx", line 3372, in NetCDF4._NetCDF4.Dimension.__init__
  File "NetCDF4/_NetCDF4.pyx", line 1891, in NetCDF4._NetCDF4._ensure_nc_success
RuntimeError: NetCDF: Not a valid ID

----------------------------------------------------------------------
\end{verbatim}

\subsection{Test tst\_diskless.py}

\begin{verbatim}
[ESDM NC] called ESDM_create:404 tmp/tmpuk5aaae_.nc 65536 0 /tmp/tmpuk5aaae_.nc
E
======================================================================
ERROR: runTest (__main__.DisklessTestCase)
testing diskless file capability
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_diskless.py", line 24, in setUp
    f = NetCDF4.Dataset(self.file,'w',diskless=True, persist=False)
  File "NetCDF4/_NetCDF4.pyx", line 2325, in NetCDF4._NetCDF4.Dataset.__init__
  File "NetCDF4/_NetCDF4.pyx", line 1889, in NetCDF4._NetCDF4._ensure_nc_success
OSError: [Errno -35] NetCDF: File exists && NC_NOCLOBBER: b'/tmp/tmpuk5aaae_.nc'

----------------------------------------------------------------------
\end{verbatim}

\subsection{Test tst\_endian.py}

\begin{verbatim}
[ESDM NC] called ESDM_def_var:1494 65536 big-little
[ESDM NC] called ESDM_def_var:1503 65536: varid: 0
0 = 0
1 = 4
E
======================================================================
ERROR: runTest (__main__.EndianTestCase)
testing endian conversion capability
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_endian.py", line 162, in runTest
    check_byteswap(self.file3, data)
  File "tst\_endian.py", line 41, in check_byteswap
    bl = dataset.createVariable('big-little', np.float32, dims, endian='big')
  File "NetCDF4/_NetCDF4.pyx", line 2772, in NetCDF4._NetCDF4.Dataset.createVariable
  File "NetCDF4/_NetCDF4.pyx", line 3875, in NetCDF4._NetCDF4.Variable.__init__
RuntimeError: only endian='native' allowed for NETCDF3 files

----------------------------------------------------------------------
\end{verbatim}

\subsection{Test tst\_enum.py}

\begin{verbatim}
[ESDM NC] called ESDM__enddef:619 65536
E
======================================================================
ERROR: runTest (__main__.EnumTestCase)
testing enum data type
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_enum.py", line 35, in setUp
    fill_value=ENUM_DICT['Missing'])
  File "NetCDF4/_NetCDF4.pyx", line 2772, in NetCDF4._NetCDF4.Dataset.createVariable
  File "NetCDF4/_NetCDF4.pyx", line 3809, in NetCDF4._NetCDF4.Variable.__init__
  File "NetCDF4/_NetCDF4.pyx", line 1891, in NetCDF4._NetCDF4._ensure_nc_success
RuntimeError: NetCDF: Not a valid data type or _FillValue type mismatch

----------------------------------------------------------------------
\end{verbatim}

\subsection{Test tst\_fancyslicing.py}

\begin{verbatim}
======================================================================
ERROR: test2unlim (__main__.VariablesTestCase)
Test with a variable that has two unlimited dimensions.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_fancyslicing.py", line 169, in test2unlim
    v[:] = data
  File "NetCDF4/_NetCDF4.pyx", line 4945, in NetCDF4._NetCDF4.Variable.__setitem__
  File "NetCDF4/_NetCDF4.pyx", line 5203, in NetCDF4._NetCDF4.Variable._put
IndexError: size of data array does not conform to slice

======================================================================
FAIL: test_get (__main__.VariablesTestCase)
testing 'fancy indexing'
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_fancyslicing.py", line 84, in test_get
    assert_array_equal(v[0:-1:2,i,:],self.data[0:-1:2,i,:])
  File "/usr/lib/python3/dist-packages/numpy/testing/utils.py", line 854, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/lib/python3/dist-packages/numpy/testing/utils.py", line 778, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

(mismatch 75.0%)
 x: MaskedArray([[[-100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
               -100],
              [-100, -100, -100, -100, -100, -100, -100, -100, -100, -100,...
 y: array([[[-300, -300, -300, -300, -300, -300, -300, -300, -300, -300, -300],
        [-300, -300, -300, -300, -300, -300, -300, -300, -300, -300, -300],
        [-300, -300, -300, -300, -300, -300, -300, -300, -300, -300, -300]],...

----------------------------------------------------------------------
Ran 3 tests in 0.039s

FAILED (failures=1, errors=1)
[ESDM NC] called ESDM_close:668 65536
[ESDM NC] called ESDM_close:668 131072
\end{verbatim}

\subsection{Test tst\_filepath.py}

\begin{verbatim}
[ESDM NC] called ESDM_open:467 home/lucy/esiwace/esdm-netcdf/dev/netcdf4-python/test/netcdf_dummy_file.nc 65536 0 /home/lucy/esiwace/esdm-netcdf/dev/netcdf4-python/test/netcdf_dummy_file.nc
E
======================================================================
ERROR: test_filepath (__main__.test_filepath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_filepath.py", line 11, in setUp
    self.nc = NetCDF4.Dataset(self.netcdf_file)
  File "NetCDF4/_NetCDF4.pyx", line 2325, in NetCDF4._NetCDF4.Dataset.__init__
  File "NetCDF4/_NetCDF4.pyx", line 1889, in NetCDF4._NetCDF4._ensure_nc_success
OSError: [Errno -77] NetCDF: Access failure: b'/home/lucy/esiwace/esdm-netcdf/dev/netcdf4-python/test/netcdf_dummy_file.nc'

======================================================================
ERROR: test_filepath_with_non_ascii_characters (__main__.test_filepath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_filepath.py", line 11, in setUp
    self.nc = NetCDF4.Dataset(self.netcdf_file)
  File "NetCDF4/_NetCDF4.pyx", line 2325, in NetCDF4._NetCDF4.Dataset.__init__
  File "NetCDF4/_NetCDF4.pyx", line 1889, in NetCDF4._NetCDF4._ensure_nc_success
OSError: [Errno -77] NetCDF: Access failure: b'/home/lucy/esiwace/esdm-netcdf/dev/netcdf4-python/test/netcdf_dummy_file.nc'

======================================================================
ERROR: test_no_such_file_raises (__main__.test_filepath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_filepath.py", line 11, in setUp
    self.nc = NetCDF4.Dataset(self.netcdf_file)
  File "NetCDF4/_NetCDF4.pyx", line 2325, in NetCDF4._NetCDF4.Dataset.__init__
  File "NetCDF4/_NetCDF4.pyx", line 1889, in NetCDF4._NetCDF4._ensure_nc_success
OSError: [Errno -77] NetCDF: Access failure: b'/home/lucy/esiwace/esdm-netcdf/dev/netcdf4-python/test/netcdf_dummy_file.nc'

----------------------------------------------------------------------
Ran 3 tests in 0.004s

FAILED (errors=3)
\end{verbatim}

\subsection{Test tst\_get\_variables\_by\_attributes.py}

\begin{verbatim}
OK

E
======================================================================
ERROR: test_find_variables_by_attribute_and_lambda (__main__.VariablesByAttributesTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_get_variables_by_attributes.py", line 10, in setUp
    self.nc = NetCDF4.Dataset(netcdf_file)
  File "NetCDF4/_NetCDF4.pyx", line 2325, in NetCDF4._NetCDF4.Dataset.__init__
  File "NetCDF4/_NetCDF4.pyx", line 1889, in NetCDF4._NetCDF4._ensure_nc_success
OSError: [Errno -77] NetCDF: Access failure: b'netcdf_dummy_file.nc'

======================================================================
ERROR: test_find_variables_by_multiple_attribute (__main__.VariablesByAttributesTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_get_variables_by_attributes.py", line 10, in setUp
    self.nc = NetCDF4.Dataset(netcdf_file)
  File "NetCDF4/_NetCDF4.pyx", line 2325, in NetCDF4._NetCDF4.Dataset.__init__
  File "NetCDF4/_NetCDF4.pyx", line 1889, in NetCDF4._NetCDF4._ensure_nc_success
OSError: [Errno -77] NetCDF: Access failure: b'netcdf_dummy_file.nc'

======================================================================
ERROR: test_find_variables_by_multiple_lambdas (__main__.VariablesByAttributesTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_get_variables_by_attributes.py", line 10, in setUp
    self.nc = NetCDF4.Dataset(netcdf_file)
  File "NetCDF4/_NetCDF4.pyx", line 2325, in NetCDF4._NetCDF4.Dataset.__init__
  File "NetCDF4/_NetCDF4.pyx", line 1889, in NetCDF4._NetCDF4._ensure_nc_success
OSError: [Errno -77] NetCDF: Access failure: b'netcdf_dummy_file.nc'

======================================================================
ERROR: test_find_variables_by_single_attribute (__main__.VariablesByAttributesTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_get_variables_by_attributes.py", line 10, in setUp
    self.nc = NetCDF4.Dataset(netcdf_file)
  File "NetCDF4/_NetCDF4.pyx", line 2325, in NetCDF4._NetCDF4.Dataset.__init__
  File "NetCDF4/_NetCDF4.pyx", line 1889, in NetCDF4._NetCDF4._ensure_nc_success
OSError: [Errno -77] NetCDF: Access failure: b'netcdf_dummy_file.nc'

======================================================================
ERROR: test_find_variables_by_single_lambda (__main__.VariablesByAttributesTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_get_variables_by_attributes.py", line 10, in setUp
    self.nc = NetCDF4.Dataset(netcdf_file)
  File "NetCDF4/_NetCDF4.pyx", line 2325, in NetCDF4._NetCDF4.Dataset.__init__
  File "NetCDF4/_NetCDF4.pyx", line 1889, in NetCDF4._NetCDF4._ensure_nc_success
OSError: [Errno -77] NetCDF: Access failure: b'netcdf_dummy_file.nc'

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (errors=5)
\end{verbatim}

\subsection{Test tst\_grps.py}

\begin{verbatim}
[ESDM NC] WARN ESDM_def_grp():2203. ESDM does not support groups from NetCDF!
E
======================================================================
ERROR: runTest (__main__.GroupsTestCase)
testing groups
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_grps.py", line 46, in setUp
    g2 = g1.createGroup(MARGARET)
  File "NetCDF4/_NetCDF4.pyx", line 2825, in NetCDF4._NetCDF4.Dataset.createGroup
  File "NetCDF4/_NetCDF4.pyx", line 3265, in NetCDF4._NetCDF4.Group.__init__
  File "NetCDF4/_NetCDF4.pyx", line 1891, in NetCDF4._NetCDF4._ensure_nc_success
RuntimeError: NetCDF: Not a valid ID

----------------------------------------------------------------------
\end{verbatim}

\subsection{Test tst\_grps2.py}

\begin{verbatim}
[ESDM NC] WARN ESDM_def_grp():2203. ESDM does not support groups from NetCDF!
E
======================================================================
ERROR: runTest (__main__.Groups2TestCase)
testing implicit group and creation and Dataset.__getitem__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_grps2.py", line 21, in setUp
    v = f.createVariable('/grouped/data/v',float,('x',))
  File "NetCDF4/_NetCDF4.pyx", line 2770, in NetCDF4._NetCDF4.Dataset.createVariable
  File "NetCDF4/_NetCDF4.pyx", line 2825, in NetCDF4._NetCDF4.Dataset.createGroup
  File "NetCDF4/_NetCDF4.pyx", line 3265, in NetCDF4._NetCDF4.Group.__init__
  File "NetCDF4/_NetCDF4.pyx", line 1891, in NetCDF4._NetCDF4._ensure_nc_success
RuntimeError: NetCDF: Not a valid ID

----------------------------------------------------------------------
\end{verbatim}

\subsection{Test tst\_issue908.py}

\begin{verbatim}
OK

[ESDM NC] called ESDM_open:467 CRM032_test1.nc 65536 0 CRM032_test1.nc
E
======================================================================
ERROR: runTest (__main__.Issue908TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_issue908.py", line 7, in setUp
    nc = NetCDF4.Dataset('CRM032_test1.nc')
  File "NetCDF4/_NetCDF4.pyx", line 2325, in NetCDF4._NetCDF4.Dataset.__init__
  File "NetCDF4/_NetCDF4.pyx", line 1889, in NetCDF4._NetCDF4._ensure_nc_success
OSError: [Errno -77] NetCDF: Access failure: b'CRM032_test1.nc'

----------------------------------------------------------------------
\end{verbatim}

\subsection{Test tst\_masked.py}

\begin{verbatim}
OK
\end{verbatim}

\subsection{Test tst\_masked2.py}

\begin{verbatim}
[ESDM NC] called ESDM_inq_att:1120 65536 name:add_offset
/usr/lib/python3/dist-packages/numpy/core/arrayprint.py:686: UserWarning: Warning: converting a masked element to nan.
  s = self.format % x
F
======================================================================
FAIL: runTest (__main__.PrimitiveTypesTestCase)
testing auto-conversion of masked arrays and packed integers
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_masked2.py", line 82, in runTest
    assert_array_almost_equal(data,datacheck1)
  File "/usr/lib/python3/dist-packages/numpy/testing/utils.py", line 962, in assert_array_almost_equal
    precision=decimal)
  File "/usr/lib/python3/dist-packages/numpy/testing/utils.py", line 778, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not almost equal to 6 decimals

(mismatch 100.0%)
 x: MaskedArray([  1.562500e+00,            nan,   3.750000e+00,   4.125000e+00], dtype=float32)
 y: MaskedArray([   nan,  5000.,  4000.,    nan])

----------------------------------------------------------------------
\end{verbatim}

\subsection{Test tst\_masked3.py}

\begin{verbatim}
[ESDM NC] called ESDM_close:668 262144
.
======================================================================
ERROR: runTest (__main__.GlobalSetAutoMaskTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_masked3.py", line 149, in setUp
    grp1.createVariable('var1', 'f8', ())
  File "NetCDF4/_NetCDF4.pyx", line 2772, in NetCDF4._NetCDF4.Dataset.createVariable
  File "NetCDF4/_NetCDF4.pyx", line 3809, in NetCDF4._NetCDF4.Variable.__init__
  File "NetCDF4/_NetCDF4.pyx", line 1891, in NetCDF4._NetCDF4._ensure_nc_success
RuntimeError: NetCDF: Not a valid ID

======================================================================
FAIL: test_scaled (__main__.SetAutoMaskFalse)
Testing auto-conversion of masked arrays for set_auto_mask(False) with scaling
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_masked3.py", line 86, in test_scaled
    self.assertEqual(v.dtype, "f8")
AssertionError: dtype('int16') != 'f8'

======================================================================
FAIL: test_scaled (__main__.SetAutoMaskTrue)
Testing auto-conversion of masked arrays for set_auto_mask(True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_masked3.py", line 129, in test_scaled
    self.assertEqual(v_ma.dtype, "f8")
AssertionError: dtype('int16') != 'f8'

----------------------------------------------------------------------
Ran 5 tests in 0.021s
\end{verbatim}

\subsection{Test tst\_masked4.py}

\begin{verbatim}
[ESDM NC] called ESDM_inq_att:1120 65536 name:add_offset
F
======================================================================
FAIL: test_scaled (__main__.SetValidMinMax)
Testing auto-conversion of masked arrays
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_masked4.py", line 87, in test_scaled
    self.assertEqual(v.dtype, "f8")
AssertionError: dtype('int16') != 'f8'

----------------------------------------------------------------------
\end{verbatim}

\subsection{Test tst\_masked5.py}

\begin{verbatim}
[ESDM NC] called ESDM_inq_var_all:1854 65536 0
E
======================================================================
ERROR: test_scaled (__main__.VectorMissingValues)
Testing auto-conversion of masked arrays
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_masked5.py", line 27, in setUp
    v2 = f.createVariable('v2',str,'x',fill_value=u'<missing>')
  File "NetCDF4/_NetCDF4.pyx", line 2772, in NetCDF4._NetCDF4.Dataset.createVariable
  File "NetCDF4/_NetCDF4.pyx", line 3741, in NetCDF4._NetCDF4.Variable.__init__
ValueError: Variable length strings are only supported for the NETCDF4 format. For other formats, consider using NetCDF4.stringtochar to convert string arrays into character arrays with an additional dimension.

----------------------------------------------------------------------
\end{verbatim}

\subsection{Test tst\_masked6.py}

\begin{verbatim}
[ESDM NC] called ESDM_close:668 131072
.
======================================================================
ERROR: runTest (__main__.GlobalSetAlwaysMaskTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_masked6.py", line 96, in setUp
    grp1.createVariable('var1', 'f8', ())
  File "NetCDF4/_NetCDF4.pyx", line 2772, in NetCDF4._NetCDF4.Dataset.createVariable
  File "NetCDF4/_NetCDF4.pyx", line 3809, in NetCDF4._NetCDF4.Variable.__init__
  File "NetCDF4/_NetCDF4.pyx", line 1891, in NetCDF4._NetCDF4._ensure_nc_success
RuntimeError: NetCDF: Not a valid ID

----------------------------------------------------------------------
\end{verbatim}

\subsection{Test tst\_multifile.py}

\begin{verbatim}
[ESDM NC] called ESDM_inq_att:1120 131072 name:add_offset
F
======================================================================
FAIL: runTest (__main__.NonuniformTimeTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_multifile.py", line 146, in runTest
    assert_equal(date2index(datetime.datetime(1980, 1, 2), T), 366)
  File "/usr/lib/python3/dist-packages/numpy/testing/utils.py", line 416, in assert_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal:
 ACTUAL: 1
 DESIRED: 366

======================================================================
FAIL: runTest (__main__.VariablesTestCase)
testing multi-file dataset access
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_multifile.py", line 52, in runTest
    assert_array_equal(np.arange(0,nx),f.variables['x'][:])
  File "/usr/lib/python3/dist-packages/numpy/testing/utils.py", line 854, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/lib/python3/dist-packages/numpy/testing/utils.py", line 778, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

(mismatch 90.0%)
 x: array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,...
 y: array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 90, 91, 92, 93, 94, 95, 96,
       97, 98, 99, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 90, 91, 92, 93,
       94, 95, 96, 97, 98, 99, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 90,...

----------------------------------------------------------------------
Ran 2 tests in 0.052s
\end{verbatim}

\subsection{Test tst\_multifile2.py}

\begin{verbatim}
[ESDM NC] called ESDM_inq_att:1120 131072 name:add_offset
F
======================================================================
FAIL: runTest (__main__.NonuniformTimeTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_multifile2.py", line 131, in runTest
    assert_equal(date2index(datetime.datetime(1980, 1, 2), T), 366)
  File "/usr/lib/python3/dist-packages/numpy/testing/utils.py", line 416, in assert_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal:
 ACTUAL: 1
 DESIRED: 366

======================================================================
FAIL: runTest (__main__.VariablesTestCase)
testing multi-file dataset access
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_multifile2.py", line 52, in runTest
    assert_array_equal(np.arange(0,nx),f.variables['x'][:])
  File "/usr/lib/python3/dist-packages/numpy/testing/utils.py", line 854, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/lib/python3/dist-packages/numpy/testing/utils.py", line 778, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

(mismatch 90.0%)
 x: array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,...
 y: array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 90, 91, 92, 93, 94, 95, 96,
       97, 98, 99, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 90, 91, 92, 93,
       94, 95, 96, 97, 98, 99, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 90,...

----------------------------------------------------------------------
Ran 2 tests in 0.070s
\end{verbatim}

\subsection{Test tst\_netcdftime.py}

\begin{verbatim}
OK
\end{verbatim}

\subsection{Test tst\_open\_mem.py}

\begin{verbatim}
[lucy-GS70-2PC-Stealth:01291] Signal: Segmentation fault (11)
\end{verbatim}

\subsection{Test tst\_refcount.py}

\begin{verbatim}
OK
\end{verbatim}

\subsection{Test tst\_rename.py}

\begin{verbatim}
[ESDM NC] WARN ESDM_def_grp():2203. ESDM does not support groups from NetCDF!
E
======================================================================
ERROR: runTest (__main__.VariablesTestCase)
testing renaming of dimensions, variables and attribute deletion
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_rename.py", line 36, in setUp
    g.createDimension(LAT_NAME,145)
  File "NetCDF4/_NetCDF4.pyx", line 2566, in NetCDF4._NetCDF4.Dataset.createDimension
  File "NetCDF4/_NetCDF4.pyx", line 3372, in NetCDF4._NetCDF4.Dimension.__init__
  File "NetCDF4/_NetCDF4.pyx", line 1891, in NetCDF4._NetCDF4._ensure_nc_success
RuntimeError: NetCDF: Not a valid ID

----------------------------------------------------------------------
\end{verbatim}

\subsection{Test tst\_scalarvar.py}

\begin{verbatim}
[ESDM NC] WARN ESDM_def_grp():2203. ESDM does not support groups from NetCDF!
E
======================================================================
ERROR: runTest (__main__.ScalarVariableTestCase)
testing scalar variables
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_scalarvar.py", line 28, in setUp
    tempg = subgroup.createVariable(VAR_NAME,VAR_TYPE)
  File "NetCDF4/_NetCDF4.pyx", line 2772, in NetCDF4._NetCDF4.Dataset.createVariable
  File "NetCDF4/_NetCDF4.pyx", line 3809, in NetCDF4._NetCDF4.Variable.__init__
  File "NetCDF4/_NetCDF4.pyx", line 1891, in NetCDF4._NetCDF4._ensure_nc_success
RuntimeError: NetCDF: Not a valid ID

----------------------------------------------------------------------
\end{verbatim}

\subsection{Test tst\_scaled.py}

\begin{verbatim}
[ESDM NC] called ESDM_close:668 65536
.
======================================================================
ERROR: runTest (__main__.GlobalSetAutoScaleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_scaled.py", line 207, in setUp
    grp1.createVariable('var1', 'f8', ())
  File "NetCDF4/_NetCDF4.pyx", line 2772, in NetCDF4._NetCDF4.Dataset.createVariable
  File "NetCDF4/_NetCDF4.pyx", line 3809, in NetCDF4._NetCDF4.Variable.__init__
  File "NetCDF4/_NetCDF4.pyx", line 1891, in NetCDF4._NetCDF4._ensure_nc_success
RuntimeError: NetCDF: Not a valid ID

======================================================================
FAIL: test_masked (__main__.SetAutoScaleTrue)
Testing auto-scaling of variables for set_auto_scale(True) with masking
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_scaled.py", line 145, in test_masked
    assert_array_almost_equal(v_ma_scaled, self.v_ma_scaled)
  File "/usr/lib/python3/dist-packages/numpy/testing/utils.py", line 962, in assert_array_almost_equal
    precision=decimal)
  File "/usr/lib/python3/dist-packages/numpy/testing/utils.py", line 778, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not almost equal to 6 decimals

(mismatch 100.0%)
 x: MaskedArray([  0.000000e+00,   5.000000e+01,   4.000000e+01,  -9.999000e+04])
 y: MaskedArray([   nan,    55.,    45.,    nan])

======================================================================
FAIL: test_unmasked (__main__.SetAutoScaleTrue)
Testing auto-scaling of variables for set_auto_scale(True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_scaled.py", line 122, in test_unmasked
    assert_array_almost_equal(v_scaled, self.v_scaled)
  File "/usr/lib/python3/dist-packages/numpy/testing/utils.py", line 962, in assert_array_almost_equal
    precision=decimal)
  File "/usr/lib/python3/dist-packages/numpy/testing/utils.py", line 778, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not almost equal to 6 decimals

(mismatch 100.0%)
 x: MaskedArray([  0.000000e+00,   5.000000e+01,   4.000000e+01,  -9.999000e+04])
 y: array([  5.000000e+00,   5.500000e+01,   4.500000e+01,  -9.998500e+04])

----------------------------------------------------------------------
Ran 6 tests in 0.039s

FAILED (failures=2, errors=1)
\end{verbatim}

\subsection{Test tst\_shape.py}

\begin{verbatim}
OK
\end{verbatim}

\subsection{Test tst\_slicing.py}

\begin{verbatim}
[ESDM NC] called ESDM_inq_dim:980 zu
E
======================================================================
ERROR: test_0d (__main__.VariablesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_slicing.py", line 33, in setUp
    vu[:,::-1,:] = data
  File "NetCDF4/_NetCDF4.pyx", line 4945, in NetCDF4._NetCDF4.Variable.__setitem__
  File "NetCDF4/_NetCDF4.pyx", line 5203, in NetCDF4._NetCDF4.Variable._put
IndexError: size of data array does not conform to slice

======================================================================
ERROR: test_1d (__main__.VariablesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_slicing.py", line 33, in setUp
    vu[:,::-1,:] = data
  File "NetCDF4/_NetCDF4.pyx", line 4945, in NetCDF4._NetCDF4.Variable.__setitem__
  File "NetCDF4/_NetCDF4.pyx", line 5203, in NetCDF4._NetCDF4.Variable._put
IndexError: size of data array does not conform to slice

======================================================================
ERROR: test_3d (__main__.VariablesTestCase)
testing variable slicing
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_slicing.py", line 33, in setUp
    vu[:,::-1,:] = data
  File "NetCDF4/_NetCDF4.pyx", line 4945, in NetCDF4._NetCDF4.Variable.__setitem__
  File "NetCDF4/_NetCDF4.pyx", line 5203, in NetCDF4._NetCDF4.Variable._put
IndexError: size of data array does not conform to slice

======================================================================
ERROR: test_issue259 (__main__.VariablesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_slicing.py", line 33, in setUp
    vu[:,::-1,:] = data
  File "NetCDF4/_NetCDF4.pyx", line 4945, in NetCDF4._NetCDF4.Variable.__setitem__
  File "NetCDF4/_NetCDF4.pyx", line 5203, in NetCDF4._NetCDF4.Variable._put
IndexError: size of data array does not conform to slice

======================================================================
ERROR: test_issue300 (__main__.VariablesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_slicing.py", line 33, in setUp
    vu[:,::-1,:] = data
  File "NetCDF4/_NetCDF4.pyx", line 4945, in NetCDF4._NetCDF4.Variable.__setitem__
  File "NetCDF4/_NetCDF4.pyx", line 5203, in NetCDF4._NetCDF4.Variable._put
IndexError: size of data array does not conform to slice

======================================================================
ERROR: test_issue306 (__main__.VariablesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_slicing.py", line 33, in setUp
    vu[:,::-1,:] = data
  File "NetCDF4/_NetCDF4.pyx", line 4945, in NetCDF4._NetCDF4.Variable.__setitem__
  File "NetCDF4/_NetCDF4.pyx", line 5203, in NetCDF4._NetCDF4.Variable._put
IndexError: size of data array does not conform to slice

======================================================================
ERROR: test_issue371 (__main__.VariablesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_slicing.py", line 33, in setUp
    vu[:,::-1,:] = data
  File "NetCDF4/_NetCDF4.pyx", line 4945, in NetCDF4._NetCDF4.Variable.__setitem__
  File "NetCDF4/_NetCDF4.pyx", line 5203, in NetCDF4._NetCDF4.Variable._put
IndexError: size of data array does not conform to slice

======================================================================
ERROR: test_issue743 (__main__.VariablesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_slicing.py", line 33, in setUp
    vu[:,::-1,:] = data
  File "NetCDF4/_NetCDF4.pyx", line 4945, in NetCDF4._NetCDF4.Variable.__setitem__
  File "NetCDF4/_NetCDF4.pyx", line 5203, in NetCDF4._NetCDF4.Variable._put
IndexError: size of data array does not conform to slice

======================================================================
ERROR: test_issue906 (__main__.VariablesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_slicing.py", line 33, in setUp
    vu[:,::-1,:] = data
  File "NetCDF4/_NetCDF4.pyx", line 4945, in NetCDF4._NetCDF4.Variable.__setitem__
  File "NetCDF4/_NetCDF4.pyx", line 5203, in NetCDF4._NetCDF4.Variable._put
IndexError: size of data array does not conform to slice

======================================================================
ERROR: test_issue919 (__main__.VariablesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_slicing.py", line 33, in setUp
    vu[:,::-1,:] = data
  File "NetCDF4/_NetCDF4.pyx", line 4945, in NetCDF4._NetCDF4.Variable.__setitem__
  File "NetCDF4/_NetCDF4.pyx", line 5203, in NetCDF4._NetCDF4.Variable._put
IndexError: size of data array does not conform to slice

======================================================================
ERROR: test_issue922 (__main__.VariablesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_slicing.py", line 33, in setUp
    vu[:,::-1,:] = data
  File "NetCDF4/_NetCDF4.pyx", line 4945, in NetCDF4._NetCDF4.Variable.__setitem__
  File "NetCDF4/_NetCDF4.pyx", line 5203, in NetCDF4._NetCDF4.Variable._put
IndexError: size of data array does not conform to slice

======================================================================
ERROR: test_retain_single_dims (__main__.VariablesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_slicing.py", line 33, in setUp
    vu[:,::-1,:] = data
  File "NetCDF4/_NetCDF4.pyx", line 4945, in NetCDF4._NetCDF4.Variable.__setitem__
  File "NetCDF4/_NetCDF4.pyx", line 5203, in NetCDF4._NetCDF4.Variable._put
IndexError: size of data array does not conform to slice

----------------------------------------------------------------------
Ran 12 tests in 0.027s
\end{verbatim}

\subsection{Test tst\_stringarr.py}

\begin{verbatim}
OK
\end{verbatim}

\subsection{Test tst\_types.py}

\begin{verbatim}
OK
\end{verbatim}

\subsection{Test tst\_unicode.py}

\begin{verbatim}
E[ESDM NC] called ESDM_close:668 65536

======================================================================
ERROR: runTest (__main__.UnicodeTestCase)
testing unicode
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_unicode.py", line 19, in setUp
    f.attribute3 = ATT3
  File "NetCDF4/_NetCDF4.pyx", line 2918, in NetCDF4._NetCDF4.Dataset.__setattr__
  File "NetCDF4/_NetCDF4.pyx", line 2848, in NetCDF4._NetCDF4.Dataset.setncattr
  File "NetCDF4/_NetCDF4.pyx", line 1587, in NetCDF4._NetCDF4._set_att
OSError: array string attributes can only be written with NETCDF4

----------------------------------------------------------------------
\end{verbatim}

\subsection{Test tst\_unicode3.py}

\begin{verbatim}
E[ESDM NC] called ESDM_close:668 65536

======================================================================
ERROR: runTest (__main__.UnicodeTestCase)
testing unicode
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_unicode3.py", line 19, in setUp
    f.attribute3 = ATT3
  File "NetCDF4/_NetCDF4.pyx", line 2918, in NetCDF4._NetCDF4.Dataset.__setattr__
  File "NetCDF4/_NetCDF4.pyx", line 2848, in NetCDF4._NetCDF4.Dataset.setncattr
  File "NetCDF4/_NetCDF4.pyx", line 1587, in NetCDF4._NetCDF4._set_att
OSError: array string attributes can only be written with NETCDF4

----------------------------------------------------------------------
\end{verbatim}

\subsection{Test tst\_unicodeatt.py}

\begin{verbatim}
E[ESDM NC] called ESDM_close:668 65536

======================================================================
ERROR: runTest (__main__.UnicodeAttTestCase)
testing unicode attributes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_unicodeatt.py", line 16, in setUp
    nc.setncattr_string('stratt3',b'\xb2`\xa4J Python')
  File "NetCDF4/_NetCDF4.pyx", line 2862, in NetCDF4._NetCDF4.Dataset.setncattr_string
OSError: file format does not support NC_STRING attributes

----------------------------------------------------------------------
\end{verbatim}

\subsection{Test tst\_unlimdim.py}

\begin{verbatim}
[ESDM NC] called ESDM_inq_dim:969 65536 5
F
======================================================================
FAIL: runTest (__main__.UnlimdimTestCase)
testing unlimited dimensions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_unlimdim.py", line 59, in runTest
    self.assertTrue(bar.shape == (n1dim,n2dim,n3dim))
AssertionError: False is not true

----------------------------------------------------------------------
\end{verbatim}

\subsection{Test tst\_Unsigned.py}

\begin{verbatim}
OK

[ESDM NC] called ESDM_open:467 ubyte.nc 65536 0 ubyte.nc
E
======================================================================
ERROR: test_unsigned (__main__.Test_Unsigned)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_Unsigned.py", line 16, in test_unsigned
    f = NetCDF4.Dataset("ubyte.nc")
  File "NetCDF4/_NetCDF4.pyx", line 2325, in NetCDF4._NetCDF4.Dataset.__init__
  File "NetCDF4/_NetCDF4.pyx", line 1889, in NetCDF4._NetCDF4._ensure_nc_success
OSError: [Errno -77] NetCDF: Access failure: b'ubyte.nc'

----------------------------------------------------------------------
Ran 1 test in 0.002s
\end{verbatim}

\subsection{Test tst\_utils.py}

\begin{verbatim}
OK
\end{verbatim}

\subsection{Test tst\_vars.py}

\begin{verbatim}
[ESDM NC] WARN ESDM_def_grp():2203. ESDM does not support groups from NetCDF!
E
======================================================================
ERROR: runTest (__main__.VariablesTestCase)
testing primitive variables
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_vars.py", line 38, in setUp
    g.createDimension(DIM1_NAME, DIM1_LEN)
  File "NetCDF4/_NetCDF4.pyx", line 2566, in NetCDF4._NetCDF4.Dataset.createDimension
  File "NetCDF4/_NetCDF4.pyx", line 3372, in NetCDF4._NetCDF4.Dimension.__init__
  File "NetCDF4/_NetCDF4.pyx", line 1891, in NetCDF4._NetCDF4._ensure_nc_success
RuntimeError: NetCDF: Not a valid ID

----------------------------------------------------------------------
\end{verbatim}

\subsection{Test tst\_vlen.py}

\begin{verbatim}
[ESDM NC] called ESDM_close:668 262144
.
======================================================================
ERROR: runTest (__main__.TestIntegerIndex)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_vlen.py", line 113, in runTest
    strtest.createVariable('tenstrings', str, ['tenstrings'])
  File "NetCDF4/_NetCDF4.pyx", line 2772, in NetCDF4._NetCDF4.Dataset.createVariable
  File "NetCDF4/_NetCDF4.pyx", line 3741, in NetCDF4._NetCDF4.Variable.__init__
ValueError: Variable length strings are only supported for the NETCDF4 format. For other formats, consider using NetCDF4.stringtochar to convert string arrays into character arrays with an additional dimension.

======================================================================
ERROR: runTest (__main__.TestObjectArrayIndexing)
testing vlen variables
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_vlen.py", line 132, in setUp
    (DIM2_NAME, DIM1_NAME))
  File "NetCDF4/_NetCDF4.pyx", line 2772, in NetCDF4._NetCDF4.Dataset.createVariable
  File "NetCDF4/_NetCDF4.pyx", line 3741, in NetCDF4._NetCDF4.Variable.__init__
ValueError: Variable length strings are only supported for the NETCDF4 format. For other formats, consider using NetCDF4.stringtochar to convert string arrays into character arrays with an additional dimension.

======================================================================
ERROR: runTest (__main__.TestScalarVlenString)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_vlen.py", line 99, in runTest
    teststring = f.createVariable('teststring', str)
  File "NetCDF4/_NetCDF4.pyx", line 2772, in NetCDF4._NetCDF4.Dataset.createVariable
  File "NetCDF4/_NetCDF4.pyx", line 3741, in NetCDF4._NetCDF4.Variable.__init__
ValueError: Variable length strings are only supported for the NETCDF4 format. For other formats, consider using NetCDF4.stringtochar to convert string arrays into character arrays with an additional dimension.

======================================================================
ERROR: runTest (__main__.VariablesTestCase)
testing vlen variables
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst\_vlen.py", line 42, in setUp
    (DIM2_NAME,DIM1_NAME))
  File "NetCDF4/_NetCDF4.pyx", line 2772, in NetCDF4._NetCDF4.Dataset.createVariable
  File "NetCDF4/_NetCDF4.pyx", line 3741, in NetCDF4._NetCDF4.Variable.__init__
ValueError: Variable length strings are only supported for the NETCDF4 format. For other formats, consider using NetCDF4.stringtochar to convert string arrays into character arrays with an additional dimension.

----------------------------------------------------------------------
Ran 6 tests in 0.008s

FAILED (errors=4)
----------------------------------------------------------------------
\end{verbatim}

\end{comment}
